version: '3'
services:
  postgres-server:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=someapi
  someapi:
    restart: on-failure
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-server
