version: '3.9'
services:
  postgres-server.internal:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  someapi:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_MAIL=${GOOGLE_MAIL}
      - GOOGLE_PASS=${GOOGLE_PASS}
      - HMAC_SECRET=${HMAC_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOST_NAME=${HOST_NAME}
    depends_on:
      - postgres-server.internal
