version: '3.9'
services:
  postgres-server:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  someapi:
    restart: on-failure
    image: ninifaroux/someapi
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_MAIL=${GOOGLE_MAIL}
      - GOOGLE_PASS=${GOOGLE_PASS}
      - HMAC_SECRET=${HMAC_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres-server
