name:                some-api
version:             0.1.0.0
github:              "githubuser/some-api"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/some-api#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-multipart
- servant-swagger
- servant-client
- swagger2
- aeson-pretty
- http-types
- http-api-data
- http-client
- rio
- persistent
- persistent-postgresql
- esqueleto
- monad-logger
- say
- wai
- warp
- mtl
- smtp-mail
- mime-mail
- ginger
- servant-auth-server
- libjwt-typed
- either
- password
- password-instances
- aeson
- record-dot-preprocessor
- record-hasfield
- monad-time
- text
- bytestring
- utf8-string
- microlens
- email-validate
- validation
- hspec
- hspec-wai
- hspec-wai-json
- optparse-applicative
- resource-pool
- dotenv

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - RecordWildCards
    - DataKinds
    - TypeOperators
    - TypeApplications
    - NoImplicitPrelude
    - FlexibleInstances

  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Wmissing-export-lists
    - -Werror


executables:
  some-api-exe:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Wmissing-export-lists
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - some-api

tests:
  some-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - some-api
