name:                some-api
version:             0.1.0.0
github:              "githubuser/some-api"
license:             BSD3
author:              "nini faroux"
copyright:           "2021 nini faroux"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/some-api#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-multipart
- servant-swagger
- servant-client
- swagger2
- aeson-pretty
- http-types
- http-api-data
- http-client
- rio
- persistent
- persistent-postgresql
- esqueleto
- monad-logger
- say
- wai
- warp
- mtl
- smtp-mail
- mime-mail
- ginger
- servant-auth-server
- libjwt-typed
- either
- password
- password-instances
- aeson
- record-dot-preprocessor
- record-hasfield
- monad-time
- text
- bytestring
- utf8-string
- microlens
- email-validate
- validation
- hspec
- hspec-wai
- hspec-wai-json
- optparse-applicative
- resource-pool
- co-log
- generic-lens

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - RecordWildCards
    - DataKinds
    - TypeOperators
    - TypeApplications
    - NoImplicitPrelude
    - FlexibleInstances

  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Wmissing-export-lists
    - -Werror


executables:
  some-api-exe:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Wmissing-export-lists
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - some-api

tests:
  integration-test:
    main: Spec.hs
    source-dirs: test/integration
    other-modules: Paths_some_api
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - some-api

  unit-test:
    main: Spec.hs
    source-dirs: test/unit
    other-modules: Paths_some_api
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - some-api
