name: docker-publish

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1
      
      - name: Login in to docker hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ninifaroux/someapi:latest
          HMAC_SECRET: ${{ secrets.hmac_secret }}
          GOOGLE_MAIL: ${{ secrets.google_mail }}
          GOOGLE_PASS: ${{ secrets.google_pass }}
          POSTGRES_USER: ${{ secrets.postgres_user }}
          POSTGRES_PASSWORD: ${{ secrets.postgres_password }}
          POSTGRES_DB: ${{ secrets.postgres_db }}
