name: docker-publish

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: "someapi"
      
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login in to docker hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # load: true
          tags: ninifaroux/someapi:latest
          secrets: |
            "HMAC_SECRET=${{ secrets.HMAC_SECRET }}"
            "GOOGLE_MAIL=${{ secrets.GOOGLE_MAIL }}"
            "GOOGLE_PASS=${{ secrets.GOOGLE_PASS }}"
            "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
            "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
            "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"

      - name: run services
        run: docker-compose up --no-build

      - name: Wait
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
